-- GENERATED by scripts/generate-catalogue.ts: do not edit by hand. Run: pnpm seed:generate
-- Fictional demo data for Afya Corner. Applied by `supabase db reset` after the migrations.

-- Settings: every key with its default, plus page text.
-- The real WhatsApp/call numbers are NOT here: put them in supabase/seed.local.sql (git-ignored).
insert into public.settings (key, value) values
  ('store_name', '"Afya Corner"'::jsonb),
  ('store_address', '"Afya Plaza, Kilimani, Nairobi"'::jsonb),
  ('whatsapp_number', '"254700000000"'::jsonb),
  ('call_number', '"0700 000 000"'::jsonb),
  ('public_email', '""'::jsonb),
  ('maps_url', '""'::jsonb),
  ('open_time', '"08:00"'::jsonb),
  ('close_time', '"21:00"'::jsonb),
  ('open_days', '[1,2,3,4,5,6,7]'::jsonb),
  ('after_hours_note', '"Our pharmacists reply from 8:00 AM. You can still send your message now."'::jsonb),
  ('hide_rx_price', 'true'::jsonb),
  ('rx_price_label', '"Price on consultation"'::jsonb),
  ('consult_message', '"Hello {store}, I would like to ask a pharmacist about {product} ({url})."'::jsonb),
  ('general_message', '"Hello {store}, I have a question."'::jsonb),
  ('stock_message', '"Hello {store}, is {product} available? ({url})"'::jsonb),
  ('order_intro', '"Hello {store}, I would like to confirm my order #{order}."'::jsonb),
  ('thankyou_text', '"Your order is saved. To confirm it, send it to our pharmacist on WhatsApp or give us a call. You pay on delivery or at pick-up."'::jsonb),
  ('p_medicine_notice', '"Your cart contains pharmacy-only medicines. A pharmacist will contact you to confirm before dispatch."'::jsonb),
  ('search_placeholder', '"Search medicines, vitamins, baby care…"'::jsonb),
  ('hero_title', '"Your neighbourhood pharmacy, online"'::jsonb),
  ('hero_text', '"Order medicines, vitamins, skin care and baby essentials. Our pharmacists are a WhatsApp message away."'::jsonb),
  ('hero_button', '"Shop now"'::jsonb),
  ('hero_image_path', '""'::jsonb),
  ('trust_points', '["Advice from registered pharmacists","Delivery across Nairobi, or pick up in Kilimani","Pay on delivery with M-Pesa or cash"]'::jsonb),
  ('categories_title', '"Shop by category"'::jsonb),
  ('featured_title', '"Popular right now"'::jsonb),
  ('featured_count', '8'::jsonb),
  ('consult_title', '"Not sure what you need?"'::jsonb),
  ('consult_text', '"Chat with our pharmacist on WhatsApp or give us a call. We are happy to help, including with prescription medicines."'::jsonb),
  ('about_text', '"Afya Corner is a neighbourhood pharmacy in Kilimani, Nairobi. Our registered pharmacists help you choose the right medicine, answer questions on WhatsApp and deliver across the city.\n\nWe keep everyday medicines, vitamins, skin care and baby essentials in stock, and we are happy to talk through prescriptions with you.\n\n(Afya Corner is a fictional pharmacy: this site is a portfolio demo and does not sell anything.)"'::jsonb),
  ('delivery_intro', '"We deliver across Nairobi, and you can always collect your order from our Kilimani pharmacy for free. You pay when your order arrives, by M-Pesa or cash."'::jsonb),
  ('delivery_times', '"Orders confirmed before 5:00 PM are delivered the same day. Orders confirmed later go out the next morning.\n\nPharmacy-only medicines are dispatched once our pharmacist has spoken to you."'::jsonb),
  ('terms_text', '"SAMPLE TEXT for a portfolio demo.\n\nOrders placed on this site are requests: a pharmacist confirms each order before it is dispatched. Prescription-only medicines are never sold online. Prices may change until your order is confirmed."'::jsonb),
  ('privacy_text', '"SAMPLE TEXT for a portfolio demo.\n\nWe use your name, phone number and address only to confirm and deliver your order. We do not sell your data. Contact us to see or delete the details we hold about you."'::jsonb);

insert into public.delivery_areas (name, fee_kes, is_pickup, sort_order) values
  ('Pick-up at our Kilimani pharmacy', 0, true, 0),
  ('Kilimani', 150, false, 1),
  ('Hurlingham', 150, false, 2),
  ('Kileleshwa', 200, false, 3),
  ('Upper Hill', 250, false, 4),
  ('Lavington', 250, false, 5),
  ('Westlands', 350, false, 6),
  ('Parklands', 350, false, 7),
  ('South B', 350, false, 8),
  ('Lang''ata', 400, false, 9),
  ('Kasarani', 450, false, 10),
  ('Karen', 500, false, 11),
  ('Ruaka', 500, false, 12);

insert into public.faqs (question, answer, sort_order) values
  ('How do I order?', 'Add products to your cart and check out. We save your order, then you send it to our pharmacist on WhatsApp (or call us) to confirm.', 0),
  ('How much is delivery?', 'It depends on where you are:

{delivery_fees}

Pick-up from our pharmacy is always free.', 1),
  ('When are you open?', '{hours}

You can send us a WhatsApp message any time; we reply when we open.', 2),
  ('How do I pay?', 'You pay on delivery or at pick-up, by M-Pesa or cash. Nothing is charged online.', 3),
  ('Can I buy prescription medicines?', 'Prescription-only medicines can''t be ordered online. Tap "Consult pharmacist" on the product and we will guide you.', 4),
  ('What does "pharmacy-only" mean?', 'Some medicines can be sold without a prescription but only after a pharmacist has checked they are right for you. We will contact you before dispatch.', 5);

insert into public.categories (slug, name, description, sort_order) values
  ('pain-fever', 'Pain & fever', 'Relief for headaches, body aches, period pain and fever.', 0),
  ('cold-flu-allergy', 'Cold, flu & allergy', 'Coughs, blocked noses, sore throats and hay fever.', 1),
  ('vitamins-supplements', 'Vitamins & supplements', 'Daily vitamins, minerals and supplements for the whole family.', 2),
  ('skin-beauty', 'Skin & beauty', 'Everyday skin care, sun protection and treatments.', 3),
  ('baby-mother', 'Baby & mother', 'Nappies, baby care and support for mums-to-be.', 4),
  ('chronic-care', 'Chronic care & devices', 'Diabetes, blood pressure and long-term medicines, with monitoring devices.', 5);

insert into public.products (sku, slug, name, short_description, description, price_kes, category_id, rx_class, in_stock, featured) values
  ('AC-00001', 'paracetamol-500mg-tablets-24s', 'Paracetamol 500mg Tablets 24s', 'Relieves mild to moderate pain and reduces fever.', 'Relieves mild to moderate pain and reduces fever. Pack size: 24s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 120, (select id from public.categories where slug = 'pain-fever'), 'general', true, true),
  ('AC-00002', 'paracetamol-500mg-tablets-100s', 'Paracetamol 500mg Tablets 100s', 'Relieves mild to moderate pain and reduces fever.', 'Relieves mild to moderate pain and reduces fever. Pack size: 100s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 380, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00003', 'ibuprofen-200mg-tablets-24s', 'Ibuprofen 200mg Tablets 24s', 'Relieves pain, inflammation and fever.', 'Relieves pain, inflammation and fever. Pack size: 24s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 180, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00004', 'ibuprofen-200mg-tablets-48s', 'Ibuprofen 200mg Tablets 48s', 'Relieves pain, inflammation and fever.', 'Relieves pain, inflammation and fever. Pack size: 48s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 320, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00005', 'ibuprofen-400mg-tablets-24s', 'Ibuprofen 400mg Tablets 24s', 'Stronger relief for pain and inflammation.', 'Stronger relief for pain and inflammation. Pack size: 24s. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 290, (select id from public.categories where slug = 'pain-fever'), 'pharmacy_only', true, false),
  ('AC-00006', 'paracetamol-children-s-suspension-120mg-5ml-60ml', 'Paracetamol Children''s Suspension 120mg/5ml 60ml', 'Pain and fever relief for children from 3 months.', 'Pain and fever relief for children from 3 months. Pack size: 60ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 220, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00007', 'paracetamol-children-s-suspension-120mg-5ml-100ml', 'Paracetamol Children''s Suspension 120mg/5ml 100ml', 'Pain and fever relief for children from 3 months.', 'Pain and fever relief for children from 3 months. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 320, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00008', 'ibuprofen-children-s-suspension-100mg-5ml-100ml', 'Ibuprofen Children''s Suspension 100mg/5ml 100ml', 'Pain and fever relief for children from 6 months.', 'Pain and fever relief for children from 6 months. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 380, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00009', 'diclofenac-1-gel-30g', 'Diclofenac 1% Gel 30g', 'Topical relief for muscle and joint pain.', 'Topical relief for muscle and joint pain. Pack size: 30g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 350, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00010', 'diclofenac-1-gel-50g', 'Diclofenac 1% Gel 50g', 'Topical relief for muscle and joint pain.', 'Topical relief for muscle and joint pain. Pack size: 50g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 520, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00011', 'diclofenac-50mg-tablets-30s', 'Diclofenac 50mg Tablets 30s', 'Prescription anti-inflammatory for joint and muscle pain.', 'Prescription anti-inflammatory for joint and muscle pain. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 420, (select id from public.categories where slug = 'pain-fever'), 'prescription_only', true, false),
  ('AC-00012', 'aspirin-75mg-dispersible-tablets-28s', 'Aspirin 75mg Dispersible Tablets 28s', 'Low-dose aspirin as directed by your doctor.', 'Low-dose aspirin as directed by your doctor. Pack size: 28s. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 150, (select id from public.categories where slug = 'pain-fever'), 'pharmacy_only', true, false),
  ('AC-00013', 'aspirin-75mg-dispersible-tablets-100s', 'Aspirin 75mg Dispersible Tablets 100s', 'Low-dose aspirin as directed by your doctor.', 'Low-dose aspirin as directed by your doctor. Pack size: 100s. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 420, (select id from public.categories where slug = 'pain-fever'), 'pharmacy_only', true, false),
  ('AC-00014', 'mefenamic-acid-500mg-tablets-20s', 'Mefenamic Acid 500mg Tablets 20s', 'Relief for period pain.', 'Relief for period pain. Pack size: 20s. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 340, (select id from public.categories where slug = 'pain-fever'), 'pharmacy_only', true, false),
  ('AC-00015', 'naproxen-500mg-tablets-28s', 'Naproxen 500mg Tablets 28s', 'Prescription anti-inflammatory for arthritis and pain.', 'Prescription anti-inflammatory for arthritis and pain. Pack size: 28s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 560, (select id from public.categories where slug = 'pain-fever'), 'prescription_only', true, false),
  ('AC-00016', 'celecoxib-200mg-capsules-30s', 'Celecoxib 200mg Capsules 30s', 'Prescription treatment for arthritis pain.', 'Prescription treatment for arthritis pain. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1450, (select id from public.categories where slug = 'pain-fever'), 'prescription_only', true, false),
  ('AC-00017', 'menthol-muscle-rub-50g', 'Menthol Muscle Rub 50g', 'Warming rub for tired and aching muscles.', 'Warming rub for tired and aching muscles. Pack size: 50g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 390, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00018', 'menthol-muscle-rub-100g', 'Menthol Muscle Rub 100g', 'Warming rub for tired and aching muscles.', 'Warming rub for tired and aching muscles. Pack size: 100g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 640, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00019', 'heat-relief-patches-5s', 'Heat Relief Patches 5s', 'Soothing warmth for back and neck pain.', 'Soothing warmth for back and neck pain. Pack size: 5s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 750, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00020', 'migraine-relief-caplets-16s', 'Migraine Relief Caplets 16s', 'Paracetamol and caffeine for headaches.', 'Paracetamol and caffeine for headaches. Pack size: 16s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 310, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00021', 'cold-pack-reusable-1-unit', 'Cold Pack Reusable 1 unit', 'Cold therapy for sprains and swelling.', 'Cold therapy for sprains and swelling. Pack size: 1 unit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 480, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00022', 'paracetamol-1g-effervescent-tablets-20s', 'Paracetamol 1g Effervescent Tablets 20s', 'Fast-dissolving pain and fever relief.', 'Fast-dissolving pain and fever relief. Pack size: 20s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 290, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00023', 'ibuprofen-5-gel-50g', 'Ibuprofen 5% Gel 50g', 'Targeted relief for sprains and strains.', 'Targeted relief for sprains and strains. Pack size: 50g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 480, (select id from public.categories where slug = 'pain-fever'), 'general', true, true),
  ('AC-00024', 'knee-support-elastic-medium', 'Knee Support Elastic Medium', 'Light support for weak or injured knees.', 'Light support for weak or injured knees. Pack size: Medium.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00025', 'knee-support-elastic-large', 'Knee Support Elastic Large', 'Light support for weak or injured knees.', 'Light support for weak or injured knees. Pack size: Large.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00026', 'warming-joint-balm-40g', 'Warming Joint Balm 40g', 'Herbal warming balm for stiff joints.', 'Herbal warming balm for stiff joints. Pack size: 40g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 420, (select id from public.categories where slug = 'pain-fever'), 'general', true, false),
  ('AC-00027', 'cetirizine-10mg-tablets-10s', 'Cetirizine 10mg Tablets 10s', 'Once-a-day relief from hay fever and allergies.', 'Once-a-day relief from hay fever and allergies. Pack size: 10s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 110, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00028', 'cetirizine-10mg-tablets-30s', 'Cetirizine 10mg Tablets 30s', 'Once-a-day relief from hay fever and allergies.', 'Once-a-day relief from hay fever and allergies. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 290, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00029', 'loratadine-10mg-tablets-10s', 'Loratadine 10mg Tablets 10s', 'Non-drowsy allergy relief.', 'Non-drowsy allergy relief. Pack size: 10s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 140, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00030', 'loratadine-10mg-tablets-30s', 'Loratadine 10mg Tablets 30s', 'Non-drowsy allergy relief.', 'Non-drowsy allergy relief. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 360, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00031', 'chlorphenamine-4mg-tablets-30s', 'Chlorphenamine 4mg Tablets 30s', 'Relief from allergy symptoms and itching.', 'Relief from allergy symptoms and itching. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 90, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00032', 'fexofenadine-180mg-tablets-10s', 'Fexofenadine 180mg Tablets 10s', 'Non-drowsy relief from severe hay fever.', 'Non-drowsy relief from severe hay fever. Pack size: 10s. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 620, (select id from public.categories where slug = 'cold-flu-allergy'), 'pharmacy_only', true, false),
  ('AC-00033', 'dry-cough-syrup-100ml', 'Dry Cough Syrup 100ml', 'Soothes dry, tickly coughs.', 'Soothes dry, tickly coughs. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 340, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00034', 'dry-cough-syrup-200ml', 'Dry Cough Syrup 200ml', 'Soothes dry, tickly coughs.', 'Soothes dry, tickly coughs. Pack size: 200ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 560, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00035', 'chesty-cough-syrup-100ml', 'Chesty Cough Syrup 100ml', 'Loosens mucus in chesty coughs.', 'Loosens mucus in chesty coughs. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 360, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00036', 'chesty-cough-syrup-200ml', 'Chesty Cough Syrup 200ml', 'Loosens mucus in chesty coughs.', 'Loosens mucus in chesty coughs. Pack size: 200ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 590, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00037', 'honey-lemon-throat-lozenges-16s', 'Honey & Lemon Throat Lozenges 16s', 'Soothes sore throats.', 'Soothes sore throats. Pack size: 16s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 220, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00038', 'honey-lemon-throat-lozenges-36s', 'Honey & Lemon Throat Lozenges 36s', 'Soothes sore throats.', 'Soothes sore throats. Pack size: 36s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 420, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00039', 'saline-nasal-spray-20ml', 'Saline Nasal Spray 20ml', 'Gently clears a blocked nose; suitable for daily use.', 'Gently clears a blocked nose; suitable for daily use. Pack size: 20ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 380, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00040', 'xylometazoline-0-1-nasal-spray-10ml', 'Xylometazoline 0.1% Nasal Spray 10ml', 'Fast relief for a blocked nose (max 7 days).', 'Fast relief for a blocked nose (max 7 days). Pack size: 10ml. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 330, (select id from public.categories where slug = 'cold-flu-allergy'), 'pharmacy_only', true, false),
  ('AC-00041', 'menthol-vapour-rub-50g', 'Menthol Vapour Rub 50g', 'Eases nasal congestion and cough.', 'Eases nasal congestion and cough. Pack size: 50g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 350, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00042', 'cold-flu-day-capsules-16s', 'Cold & Flu Day Capsules 16s', 'Relieves fever, aches and congestion.', 'Relieves fever, aches and congestion. Pack size: 16s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 420, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, true),
  ('AC-00043', 'steam-inhaler-capsules-10s', 'Steam Inhaler Capsules 10s', 'Aromatic oils for steam inhalation.', 'Aromatic oils for steam inhalation. Pack size: 10s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 290, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00044', 'amoxicillin-500mg-capsules-15s', 'Amoxicillin 500mg Capsules 15s', 'Prescription antibiotic for bacterial infections.', 'Prescription antibiotic for bacterial infections. Pack size: 15s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 380, (select id from public.categories where slug = 'cold-flu-allergy'), 'prescription_only', true, false),
  ('AC-00045', 'amoxicillin-500mg-capsules-21s', 'Amoxicillin 500mg Capsules 21s', 'Prescription antibiotic for bacterial infections.', 'Prescription antibiotic for bacterial infections. Pack size: 21s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 480, (select id from public.categories where slug = 'cold-flu-allergy'), 'prescription_only', true, false),
  ('AC-00046', 'azithromycin-500mg-tablets-3s', 'Azithromycin 500mg Tablets 3s', 'Prescription antibiotic for bacterial infections.', 'Prescription antibiotic for bacterial infections. Pack size: 3s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 520, (select id from public.categories where slug = 'cold-flu-allergy'), 'prescription_only', true, false),
  ('AC-00047', 'prednisolone-5mg-tablets-30s', 'Prednisolone 5mg Tablets 30s', 'Prescription steroid for inflammation and allergy.', 'Prescription steroid for inflammation and allergy. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 260, (select id from public.categories where slug = 'cold-flu-allergy'), 'prescription_only', true, false),
  ('AC-00048', 'antiseptic-throat-spray-30ml', 'Antiseptic Throat Spray 30ml', 'Numbs and soothes painful sore throats.', 'Numbs and soothes painful sore throats. Pack size: 30ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 540, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00049', 'montelukast-10mg-tablets-30s', 'Montelukast 10mg Tablets 30s', 'Prescription medicine for asthma and allergic rhinitis.', 'Prescription medicine for asthma and allergic rhinitis. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'cold-flu-allergy'), 'prescription_only', true, false),
  ('AC-00050', 'beclometasone-nasal-spray-200-doses', 'Beclometasone Nasal Spray 200 doses', 'Prevents and treats hay fever symptoms.', 'Prevents and treats hay fever symptoms. Pack size: 200 doses. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 740, (select id from public.categories where slug = 'cold-flu-allergy'), 'pharmacy_only', true, false),
  ('AC-00051', 'children-s-cough-syrup-100ml', 'Children''s Cough Syrup 100ml', 'Gentle, sugar-free cough relief for children 2+.', 'Gentle, sugar-free cough relief for children 2+. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 390, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00052', 'zinc-vitamin-c-lozenges-24s', 'Zinc & Vitamin C Lozenges 24s', 'Soothes the throat and supports immunity.', 'Soothes the throat and supports immunity. Pack size: 24s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 450, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00053', 'disposable-face-masks-10s', 'Disposable Face Masks 10s', '3-ply masks for everyday protection.', '3-ply masks for everyday protection. Pack size: 10s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 150, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', false, false),
  ('AC-00054', 'disposable-face-masks-50s', 'Disposable Face Masks 50s', '3-ply masks for everyday protection.', '3-ply masks for everyday protection. Pack size: 50s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 590, (select id from public.categories where slug = 'cold-flu-allergy'), 'general', true, false),
  ('AC-00055', 'vitamin-c-1000mg-effervescent-tablets-20s', 'Vitamin C 1000mg Effervescent Tablets 20s', 'Supports the immune system.', 'Supports the immune system. Pack size: 20s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 850, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00056', 'vitamin-c-1000mg-effervescent-tablets-2-x-20s', 'Vitamin C 1000mg Effervescent Tablets 2 x 20s', 'Supports the immune system.', 'Supports the immune system. Pack size: 2 x 20s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1550, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00057', 'vitamin-d3-1000iu-softgels-60s', 'Vitamin D3 1000IU Softgels 60s', 'Supports bones, teeth and immunity.', 'Supports bones, teeth and immunity. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 990, (select id from public.categories where slug = 'vitamins-supplements'), 'general', false, false),
  ('AC-00058', 'vitamin-d3-1000iu-softgels-120s', 'Vitamin D3 1000IU Softgels 120s', 'Supports bones, teeth and immunity.', 'Supports bones, teeth and immunity. Pack size: 120s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1690, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00059', 'adult-multivitamin-tablets-30s', 'Adult Multivitamin Tablets 30s', 'A daily multivitamin and mineral for adults.', 'A daily multivitamin and mineral for adults. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1100, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00060', 'adult-multivitamin-tablets-90s', 'Adult Multivitamin Tablets 90s', 'A daily multivitamin and mineral for adults.', 'A daily multivitamin and mineral for adults. Pack size: 90s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2750, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00061', 'kids-multivitamin-gummies-60s', 'Kids'' Multivitamin Gummies 60s', 'Fruit-flavoured daily vitamins for children 3+.', 'Fruit-flavoured daily vitamins for children 3+. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1350, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00062', 'zinc-15mg-tablets-30s', 'Zinc 15mg Tablets 30s', 'Supports immunity, skin and hair.', 'Supports immunity, skin and hair. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 520, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00063', 'iron-folic-acid-tablets-30s', 'Iron & Folic Acid Tablets 30s', 'Helps reduce tiredness and fatigue.', 'Helps reduce tiredness and fatigue. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 380, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00064', 'iron-folic-acid-tablets-90s', 'Iron & Folic Acid Tablets 90s', 'Helps reduce tiredness and fatigue.', 'Helps reduce tiredness and fatigue. Pack size: 90s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 950, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00065', 'calcium-vitamin-d3-tablets-60s', 'Calcium + Vitamin D3 Tablets 60s', 'Supports strong bones.', 'Supports strong bones. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 870, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00066', 'omega-3-fish-oil-1000mg-capsules-60s', 'Omega-3 Fish Oil 1000mg Capsules 60s', 'Supports heart and brain health.', 'Supports heart and brain health. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1250, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, true),
  ('AC-00067', 'omega-3-fish-oil-1000mg-capsules-120s', 'Omega-3 Fish Oil 1000mg Capsules 120s', 'Supports heart and brain health.', 'Supports heart and brain health. Pack size: 120s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2150, (select id from public.categories where slug = 'vitamins-supplements'), 'general', false, false),
  ('AC-00068', 'magnesium-250mg-tablets-60s', 'Magnesium 250mg Tablets 60s', 'Supports muscles and reduces tiredness.', 'Supports muscles and reduces tiredness. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 940, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00069', 'vitamin-b-complex-tablets-30s', 'Vitamin B-Complex Tablets 30s', 'Supports energy release and the nervous system.', 'Supports energy release and the nervous system. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 620, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00070', 'probiotic-capsules-30s', 'Probiotic Capsules 30s', 'Supports a healthy gut.', 'Supports a healthy gut. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1650, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00071', 'marine-collagen-powder-150g', 'Marine Collagen Powder 150g', 'Supports skin, hair and nails.', 'Supports skin, hair and nails. Pack size: 150g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2950, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00072', 'biotin-5000mcg-tablets-60s', 'Biotin 5000mcg Tablets 60s', 'Supports healthy hair and nails.', 'Supports healthy hair and nails. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1150, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00073', 'glucosamine-1500mg-tablets-60s', 'Glucosamine 1500mg Tablets 60s', 'Supports joint health.', 'Supports joint health. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1890, (select id from public.categories where slug = 'vitamins-supplements'), 'general', false, false),
  ('AC-00074', 'energy-drink-powder-sachets-10s', 'Energy Drink Powder Sachets 10s', 'Electrolytes and B vitamins for busy days.', 'Electrolytes and B vitamins for busy days. Pack size: 10s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 690, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00075', 'vitamin-b12-1000mcg-tablets-60s', 'Vitamin B12 1000mcg Tablets 60s', 'Supports energy and red blood cell formation.', 'Supports energy and red blood cell formation. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00076', 'cod-liver-oil-capsules-60s', 'Cod Liver Oil Capsules 60s', 'Vitamins A and D with omega-3.', 'Vitamins A and D with omega-3. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 780, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00077', 'folic-acid-400mcg-tablets-90s', 'Folic Acid 400mcg Tablets 90s', 'Recommended before and during early pregnancy.', 'Recommended before and during early pregnancy. Pack size: 90s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 350, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00078', 'turmeric-black-pepper-capsules-60s', 'Turmeric & Black Pepper Capsules 60s', 'A traditional supplement for joint comfort.', 'A traditional supplement for joint comfort. Pack size: 60s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1290, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, false),
  ('AC-00079', 'electrolyte-effervescent-tablets-20s', 'Electrolyte Effervescent Tablets 20s', 'Rehydration after exercise or heat.', 'Rehydration after exercise or heat. Pack size: 20s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 590, (select id from public.categories where slug = 'vitamins-supplements'), 'general', true, true),
  ('AC-00080', 'sunscreen-spf-50-lotion-100ml', 'Sunscreen SPF 50 Lotion 100ml', 'Broad-spectrum protection for face and body.', 'Broad-spectrum protection for face and body. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1650, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00081', 'sunscreen-spf-50-lotion-200ml', 'Sunscreen SPF 50 Lotion 200ml', 'Broad-spectrum protection for face and body.', 'Broad-spectrum protection for face and body. Pack size: 200ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2690, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00082', 'daily-moisturising-cream-100ml', 'Daily Moisturising Cream 100ml', 'Light, fragrance-free moisturiser for dry skin.', 'Light, fragrance-free moisturiser for dry skin. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00083', 'daily-moisturising-cream-400ml', 'Daily Moisturising Cream 400ml', 'Light, fragrance-free moisturiser for dry skin.', 'Light, fragrance-free moisturiser for dry skin. Pack size: 400ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2150, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00084', 'aqueous-cream-100g', 'Aqueous Cream 100g', 'Soap substitute and moisturiser for dry skin.', 'Soap substitute and moisturiser for dry skin. Pack size: 100g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 290, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00085', 'aqueous-cream-500g', 'Aqueous Cream 500g', 'Soap substitute and moisturiser for dry skin.', 'Soap substitute and moisturiser for dry skin. Pack size: 500g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 780, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00086', 'petroleum-jelly-100ml', 'Petroleum Jelly 100ml', 'Protects and soothes dry, chapped skin.', 'Protects and soothes dry, chapped skin. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 210, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00087', 'petroleum-jelly-250ml', 'Petroleum Jelly 250ml', 'Protects and soothes dry, chapped skin.', 'Protects and soothes dry, chapped skin. Pack size: 250ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 390, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00088', 'hydrocortisone-1-cream-15g', 'Hydrocortisone 1% Cream 15g', 'Relieves itching and mild eczema.', 'Relieves itching and mild eczema. Pack size: 15g. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 450, (select id from public.categories where slug = 'skin-beauty'), 'pharmacy_only', true, false),
  ('AC-00089', 'clotrimazole-1-cream-20g', 'Clotrimazole 1% Cream 20g', 'Treats fungal skin infections such as athlete''s foot.', 'Treats fungal skin infections such as athlete''s foot. Pack size: 20g. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 280, (select id from public.categories where slug = 'skin-beauty'), 'pharmacy_only', true, false),
  ('AC-00090', 'benzoyl-peroxide-5-gel-30g', 'Benzoyl Peroxide 5% Gel 30g', 'Treats mild to moderate acne.', 'Treats mild to moderate acne. Pack size: 30g. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 690, (select id from public.categories where slug = 'skin-beauty'), 'pharmacy_only', true, false),
  ('AC-00091', 'tretinoin-0-025-cream-20g', 'Tretinoin 0.025% Cream 20g', 'Prescription treatment for acne.', 'Prescription treatment for acne. Pack size: 20g. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 980, (select id from public.categories where slug = 'skin-beauty'), 'prescription_only', true, false),
  ('AC-00092', 'calamine-lotion-100ml', 'Calamine Lotion 100ml', 'Soothes itchy skin, bites and rashes.', 'Soothes itchy skin, bites and rashes. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 240, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00093', 'antiseptic-cream-30g', 'Antiseptic Cream 30g', 'Helps prevent infection in minor cuts and grazes.', 'Helps prevent infection in minor cuts and grazes. Pack size: 30g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 320, (select id from public.categories where slug = 'skin-beauty'), 'general', false, false),
  ('AC-00094', 'gentle-foaming-face-wash-150ml', 'Gentle Foaming Face Wash 150ml', 'Cleans without drying; for oily and combination skin.', 'Cleans without drying; for oily and combination skin. Pack size: 150ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 850, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00095', 'shea-butter-body-lotion-400ml', 'Shea Butter Body Lotion 400ml', 'Rich moisture for very dry skin.', 'Rich moisture for very dry skin. Pack size: 400ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 990, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00096', 'spf-30-lip-balm-4g', 'SPF 30 Lip Balm 4g', 'Protects and softens lips.', 'Protects and softens lips. Pack size: 4g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 350, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00097', 'adhesive-plasters-assorted-20s', 'Adhesive Plasters Assorted 20s', 'Covers minor cuts and blisters.', 'Covers minor cuts and blisters. Pack size: 20s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 180, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00098', 'adhesive-plasters-assorted-40s', 'Adhesive Plasters Assorted 40s', 'Covers minor cuts and blisters.', 'Covers minor cuts and blisters. Pack size: 40s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 320, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00099', 'first-aid-kit-travel-1-kit', 'First Aid Kit Travel 1 kit', 'Plasters, dressings and wipes for small injuries.', 'Plasters, dressings and wipes for small injuries. Pack size: 1 kit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1450, (select id from public.categories where slug = 'skin-beauty'), 'general', true, true),
  ('AC-00100', 'micellar-cleansing-water-250ml', 'Micellar Cleansing Water 250ml', 'Removes make-up and cleanses in one step.', 'Removes make-up and cleanses in one step. Pack size: 250ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 990, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00101', 'anti-dandruff-shampoo-200ml', 'Anti-dandruff Shampoo 200ml', 'Controls flaking and itchy scalp.', 'Controls flaking and itchy scalp. Pack size: 200ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 750, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00102', 'insect-repellent-lotion-100ml', 'Insect Repellent Lotion 100ml', 'Protects against mosquito bites for up to 8 hours.', 'Protects against mosquito bites for up to 8 hours. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 690, (select id from public.categories where slug = 'skin-beauty'), 'general', true, false),
  ('AC-00103', 'aloe-vera-after-sun-gel-200ml', 'Aloe Vera After-sun Gel 200ml', 'Cools and soothes sun-exposed skin.', 'Cools and soothes sun-exposed skin. Pack size: 200ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 720, (select id from public.categories where slug = 'skin-beauty'), 'general', false, false),
  ('AC-00104', 'mupirocin-2-ointment-15g', 'Mupirocin 2% Ointment 15g', 'Prescription antibiotic ointment for skin infections.', 'Prescription antibiotic ointment for skin infections. Pack size: 15g. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 690, (select id from public.categories where slug = 'skin-beauty'), 'prescription_only', true, false),
  ('AC-00105', 'baby-nappies-size-2-3-6kg-44s', 'Baby Nappies Size 2 (3–6kg) 44s', 'Soft, absorbent nappies for newborns.', 'Soft, absorbent nappies for newborns. Pack size: 44s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1350, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00106', 'baby-nappies-size-3-5-9kg-40s', 'Baby Nappies Size 3 (5–9kg) 40s', 'Up to 12 hours of dryness.', 'Up to 12 hours of dryness. Pack size: 40s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1390, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00107', 'baby-nappies-size-3-5-9kg-80s', 'Baby Nappies Size 3 (5–9kg) 80s', 'Up to 12 hours of dryness.', 'Up to 12 hours of dryness. Pack size: 80s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2590, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00108', 'baby-nappies-size-4-8-14kg-36s', 'Baby Nappies Size 4 (8–14kg) 36s', 'Stretchy sides for active babies.', 'Stretchy sides for active babies. Pack size: 36s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1450, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00109', 'baby-nappies-size-4-8-14kg-72s', 'Baby Nappies Size 4 (8–14kg) 72s', 'Stretchy sides for active babies.', 'Stretchy sides for active babies. Pack size: 72s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2690, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00110', 'fragrance-free-baby-wipes-64s', 'Fragrance-free Baby Wipes 64s', 'Gentle cleansing for sensitive skin.', 'Gentle cleansing for sensitive skin. Pack size: 64s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 290, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00111', 'fragrance-free-baby-wipes-3-x-64s', 'Fragrance-free Baby Wipes 3 x 64s', 'Gentle cleansing for sensitive skin.', 'Gentle cleansing for sensitive skin. Pack size: 3 x 64s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 790, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00112', 'nappy-rash-cream-50g', 'Nappy Rash Cream 50g', 'Soothes and protects against nappy rash.', 'Soothes and protects against nappy rash. Pack size: 50g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 480, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00113', 'baby-lotion-200ml', 'Baby Lotion 200ml', 'Mild moisturiser for baby skin.', 'Mild moisturiser for baby skin. Pack size: 200ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 520, (select id from public.categories where slug = 'baby-mother'), 'general', false, false),
  ('AC-00114', 'infant-paracetamol-drops-100mg-ml-15ml', 'Infant Paracetamol Drops 100mg/ml 15ml', 'Fever and pain relief for infants from 3 months.', 'Fever and pain relief for infants from 3 months. Pack size: 15ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 260, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00115', 'oral-rehydration-salts-10-sachets', 'Oral Rehydration Salts 10 sachets', 'Replaces fluids and salts lost through diarrhoea.', 'Replaces fluids and salts lost through diarrhoea. Pack size: 10 sachets.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 250, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00116', 'gripe-water-150ml', 'Gripe Water 150ml', 'Traditional relief for wind and colic.', 'Traditional relief for wind and colic. Pack size: 150ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 390, (select id from public.categories where slug = 'baby-mother'), 'general', true, true),
  ('AC-00117', 'teething-gel-10g', 'Teething Gel 10g', 'Soothes sore gums during teething.', 'Soothes sore gums during teething. Pack size: 10g. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 450, (select id from public.categories where slug = 'baby-mother'), 'pharmacy_only', true, false),
  ('AC-00118', 'pregnancy-multivitamin-tablets-30s', 'Pregnancy Multivitamin Tablets 30s', 'Folic acid, iron and vitamins for pregnancy.', 'Folic acid, iron and vitamins for pregnancy. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1290, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00119', 'disposable-breast-pads-30s', 'Disposable Breast Pads 30s', 'Absorbent, discreet protection.', 'Absorbent, discreet protection. Pack size: 30s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 650, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00120', 'anti-colic-feeding-bottle-260ml-1-bottle', 'Anti-colic Feeding Bottle 260ml 1 bottle', 'Vented bottle to reduce feeding wind.', 'Vented bottle to reduce feeding wind. Pack size: 1 bottle.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00121', 'digital-baby-thermometer-1-unit', 'Digital Baby Thermometer 1 unit', 'Fast, flexible-tip thermometer.', 'Fast, flexible-tip thermometer. Pack size: 1 unit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 750, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00122', 'pregnancy-test-strips-2-tests', 'Pregnancy Test Strips 2 tests', 'Early result pregnancy test.', 'Early result pregnancy test. Pack size: 2 tests.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 350, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00123', 'baby-nappies-size-5-11-25kg-32s', 'Baby Nappies Size 5 (11–25kg) 32s', 'Extra absorbency for toddlers.', 'Extra absorbency for toddlers. Pack size: 32s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1490, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00124', 'baby-shampoo-tear-free-200ml', 'Baby Shampoo Tear-free 200ml', 'Gentle cleansing for hair and body.', 'Gentle cleansing for hair and body. Pack size: 200ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 450, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00125', 'nasal-aspirator-for-babies-1-unit', 'Nasal Aspirator for Babies 1 unit', 'Gently clears a baby''s blocked nose.', 'Gently clears a baby''s blocked nose. Pack size: 1 unit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 650, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00126', 'nipple-care-cream-30g', 'Nipple Care Cream 30g', 'Soothes and protects sore nipples.', 'Soothes and protects sore nipples. Pack size: 30g.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00127', 'maternity-pads-10s', 'Maternity Pads 10s', 'Extra-absorbent pads for after birth.', 'Extra-absorbent pads for after birth. Pack size: 10s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 390, (select id from public.categories where slug = 'baby-mother'), 'general', true, false),
  ('AC-00128', 'metformin-500mg-tablets-30s', 'Metformin 500mg Tablets 30s', 'Prescription medicine for type 2 diabetes.', 'Prescription medicine for type 2 diabetes. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 190, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00129', 'metformin-500mg-tablets-100s', 'Metformin 500mg Tablets 100s', 'Prescription medicine for type 2 diabetes.', 'Prescription medicine for type 2 diabetes. Pack size: 100s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 540, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00130', 'amlodipine-5mg-tablets-30s', 'Amlodipine 5mg Tablets 30s', 'Prescription medicine for high blood pressure.', 'Prescription medicine for high blood pressure. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 240, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00131', 'losartan-50mg-tablets-30s', 'Losartan 50mg Tablets 30s', 'Prescription medicine for high blood pressure.', 'Prescription medicine for high blood pressure. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 420, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00132', 'atorvastatin-20mg-tablets-30s', 'Atorvastatin 20mg Tablets 30s', 'Prescription medicine to lower cholesterol.', 'Prescription medicine to lower cholesterol. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 480, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00133', 'levothyroxine-50mcg-tablets-28s', 'Levothyroxine 50mcg Tablets 28s', 'Prescription thyroid hormone replacement.', 'Prescription thyroid hormone replacement. Pack size: 28s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 360, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00134', 'salbutamol-100mcg-inhaler-200-doses', 'Salbutamol 100mcg Inhaler 200 doses', 'Prescription reliever inhaler for asthma.', 'Prescription reliever inhaler for asthma. Pack size: 200 doses. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 590, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00135', 'omeprazole-20mg-capsules-14s', 'Omeprazole 20mg Capsules 14s', 'Relief from heartburn and acid reflux.', 'Relief from heartburn and acid reflux. Pack size: 14s. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 290, (select id from public.categories where slug = 'chronic-care'), 'pharmacy_only', true, false),
  ('AC-00136', 'omeprazole-20mg-capsules-28s', 'Omeprazole 20mg Capsules 28s', 'Relief from heartburn and acid reflux.', 'Relief from heartburn and acid reflux. Pack size: 28s. Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 520, (select id from public.categories where slug = 'chronic-care'), 'pharmacy_only', true, false),
  ('AC-00137', 'antacid-chewable-tablets-24s', 'Antacid Chewable Tablets 24s', 'Fast relief from indigestion.', 'Fast relief from indigestion. Pack size: 24s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 230, (select id from public.categories where slug = 'chronic-care'), 'general', true, true),
  ('AC-00138', 'blood-glucose-meter-1-kit', 'Blood Glucose Meter 1 kit', 'Easy home testing of blood sugar.', 'Easy home testing of blood sugar. Pack size: 1 kit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2650, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00139', 'blood-glucose-test-strips-50s', 'Blood Glucose Test Strips 50s', 'For use with the Afya Care glucose meter.', 'For use with the Afya Care glucose meter. Pack size: 50s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2150, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00140', 'lancets-30g-100s', 'Lancets 30G 100s', 'Sterile lancets for finger-prick testing.', 'Sterile lancets for finger-prick testing. Pack size: 100s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 690, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00141', 'upper-arm-blood-pressure-monitor-1-unit', 'Upper Arm Blood Pressure Monitor 1 unit', 'Automatic, clinically validated BP readings.', 'Automatic, clinically validated BP readings. Pack size: 1 unit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 5450, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00142', 'pulse-oximeter-1-unit', 'Pulse Oximeter 1 unit', 'Measures oxygen saturation and pulse.', 'Measures oxygen saturation and pulse. Pack size: 1 unit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 2450, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00143', 'weekly-pill-organiser-1-unit', 'Weekly Pill Organiser 1 unit', 'Morning and evening compartments for 7 days.', 'Morning and evening compartments for 7 days. Pack size: 1 unit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 450, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00144', 'digital-thermometer-1-unit', 'Digital Thermometer 1 unit', 'Oral or underarm temperature in seconds.', 'Oral or underarm temperature in seconds. Pack size: 1 unit.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 480, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00145', 'metformin-850mg-tablets-60s', 'Metformin 850mg Tablets 60s', 'Prescription medicine for type 2 diabetes.', 'Prescription medicine for type 2 diabetes. Pack size: 60s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 390, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00146', 'hydrochlorothiazide-25mg-tablets-30s', 'Hydrochlorothiazide 25mg Tablets 30s', 'Prescription medicine for high blood pressure.', 'Prescription medicine for high blood pressure. Pack size: 30s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 180, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false),
  ('AC-00147', 'glucose-tablets-10s', 'Glucose Tablets 10s', 'Fast sugar for low blood glucose.', 'Fast sugar for low blood glucose. Pack size: 10s.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 250, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00148', 'diabetic-foot-cream-100ml', 'Diabetic Foot Cream 100ml', 'Moisturises very dry skin on the feet.', 'Moisturises very dry skin on the feet. Pack size: 100ml.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 890, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00149', 'compression-socks-medium', 'Compression Socks Medium', 'Improves circulation on long journeys.', 'Improves circulation on long journeys. Pack size: Medium.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1290, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00150', 'compression-socks-large', 'Compression Socks Large', 'Improves circulation on long journeys.', 'Improves circulation on long journeys. Pack size: Large.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 1290, (select id from public.categories where slug = 'chronic-care'), 'general', true, false),
  ('AC-00151', 'mesalazine-400mg-tablets-90s', 'Mesalazine 400mg Tablets 90s', 'Prescription medicine for inflammatory bowel disease.', 'Prescription medicine for inflammatory bowel disease. Pack size: 90s. Prescription-only: talk to our pharmacist to order it.

Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, pregnant, breastfeeding or taking other medicines.

Afya Corner is a fictional pharmacy; this product is demo data.', 3250, (select id from public.categories where slug = 'chronic-care'), 'prescription_only', true, false);
