-- GENERATED by scripts/generate-catalogue.ts from scripts/test-users.ts. LOCAL DEVELOPMENT ONLY.
-- Loaded by `supabase db reset` (sql_paths in config.toml). Never apply to the cloud database.

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, recovery_token, email_change_token_new, email_change) values
  ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-00000000a0a1', 'authenticated', 'authenticated', 'owner@afya-corner.test', extensions.crypt('local-owner-2026', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Test Owner"}'::jsonb, now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-00000000a0a2', 'authenticated', 'authenticated', 'staff@afya-corner.test', extensions.crypt('local-staff-2026', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Test Pharmacist"}'::jsonb, now(), now(), '', '', '', '');

insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at) values
  (gen_random_uuid(), '00000000-0000-4000-8000-00000000a0a1', '00000000-0000-4000-8000-00000000a0a1', '{"sub":"00000000-0000-4000-8000-00000000a0a1","email":"owner@afya-corner.test","email_verified":true}'::jsonb, 'email', now(), now(), now()),
  (gen_random_uuid(), '00000000-0000-4000-8000-00000000a0a2', '00000000-0000-4000-8000-00000000a0a2', '{"sub":"00000000-0000-4000-8000-00000000a0a2","email":"staff@afya-corner.test","email_verified":true}'::jsonb, 'email', now(), now(), now());

insert into public.profiles (id, role, full_name) values
  ('00000000-0000-4000-8000-00000000a0a1', 'owner', 'Test Owner'),
  ('00000000-0000-4000-8000-00000000a0a2', 'staff', 'Test Pharmacist');
