/**
 * Generates supabase/seed.sql: categories, ~150 fictional products, delivery areas, settings and FAQs.
 * Deterministic (seeded random numbers), so every run produces the same file.
 *
 *   pnpm seed:generate   then   pnpm db:reset
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { catalogue } from "./catalogue-data";
import { deliveryAreas, faqs, pageText } from "./content-data";
import { defaultSettings } from "../src/lib/settings/schema";

/** mulberry32: tiny seeded PRNG, so "random" stock levels are the same on every run. */
function prng(seed: number) {
  return () => {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const sql = (value: string | null) => (value === null ? "null" : `'${value.replace(/'/g, "''")}'`);
const json = (value: unknown) => `${sql(JSON.stringify(value))}::jsonb`;
const slugify = (text: string) =>
  text
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const RX_NOTE: Record<string, string> = {
  general: "",
  pharmacy_only: " Pharmacy-only: our pharmacist will confirm it is right for you before dispatch.",
  prescription_only: " Prescription-only: talk to our pharmacist to order it.",
};

const random = prng(20260930);
const products: string[] = [];
const featuredCandidates: number[] = [];
let n = 0;

for (const category of catalogue) {
  for (const base of category.products) {
    for (const [pack, price] of base.variants) {
      n += 1;
      const rx = base.rx ?? "general";
      const name = `${base.name} ${pack}`;
      // ~7% out of stock, never the first product of a category (keeps category pages lively)
      const inStock = n % 25 === 1 || random() > 0.07;
      if (inStock && rx === "general" && base.variants[0][0] === pack) featuredCandidates.push(n);
      const description =
        `${base.use}. Pack size: ${pack}.${RX_NOTE[rx]}\n\n` +
        "Always read the label and the patient information leaflet. Ask our pharmacist if you are unsure, " +
        "pregnant, breastfeeding or taking other medicines.\n\n" +
        "Afya Corner is a fictional pharmacy; this product is demo data.";
      products.push(
        `(${sql(`AC-${String(n).padStart(5, "0")}`)}, ${sql(slugify(name))}, ${sql(name)}, ${sql(`${base.use}.`)}, ` +
          `${sql(description)}, ${price}, (select id from public.categories where slug = ${sql(category.slug)}), ` +
          `'${rx}', ${inStock}, {featured:${n}})`,
      );
    }
  }
}

// Eight featured products spread across the catalogue
const step = featuredCandidates.length / 8;
const featured = new Set(Array.from({ length: 8 }, (_, i) => featuredCandidates[Math.floor(i * step)]));
const productRows = products.map((row, i) => row.replace(`{featured:${i + 1}}`, String(featured.has(i + 1))));

const settings = { ...defaultSettings, ...pageText };

const out = `-- GENERATED by scripts/generate-catalogue.ts: do not edit by hand. Run: pnpm seed:generate
-- Fictional demo data for Afya Corner. Applied by \`supabase db reset\` after the migrations.

-- Settings: every key with its default, plus page text.
-- The real WhatsApp/call numbers are NOT here: put them in supabase/seed.local.sql (git-ignored).
insert into public.settings (key, value) values
${Object.entries(settings)
  .map(([key, value]) => `  (${sql(key)}, ${json(value)})`)
  .join(",\n")};

insert into public.delivery_areas (name, fee_kes, is_pickup, sort_order) values
${deliveryAreas.map(([name, fee, pickup], i) => `  (${sql(name)}, ${fee}, ${pickup}, ${i})`).join(",\n")};

insert into public.faqs (question, answer, sort_order) values
${faqs.map(([q, a], i) => `  (${sql(q)}, ${sql(a)}, ${i})`).join(",\n")};

insert into public.categories (slug, name, description, sort_order) values
${catalogue.map((c, i) => `  (${sql(c.slug)}, ${sql(c.name)}, ${sql(c.description)}, ${i})`).join(",\n")};

insert into public.products (sku, slug, name, short_description, description, price_kes, category_id, rx_class, in_stock, featured) values
${productRows.map((r) => `  ${r}`).join(",\n")};
`;

const file = join(import.meta.dirname, "..", "supabase", "seed.sql");
writeFileSync(file, out);
const counts = catalogue.map((c) => `${c.slug}: ${c.products.reduce((s, p) => s + p.variants.length, 0)}`);
console.log(`Wrote ${file}\n${n} products (${counts.join(", ")}), ${featured.size} featured`);
